
server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Wanxiangdai2018
    url: jdbc:mysql://bj-cdb-98fxjfrh.sql.tencentcdb.com:63617/iou?characterEncoding=utf-8
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

mybatis:
    mapper-locations: classpath:/mappers/*.xml
    type-aliases-package: com.xjyq.pojo,com.xjyq.bo,com.xjyq.vo

db:
   driverLocation: C:/Users/Administrator/.m2/repository/mysql/mysql-connector-java/5.1.6/mysql-connector-java-5.1.6.jar
   driverClassName: com.mysql.jdbc.Driver
   url: jdbc:mysql://bj-cdb-98fxjfrh.sql.tencentcdb.com:63617/iou?characterEncoding=utf-8
   username: root
   password: Wanxiangdai2018

Spring:
       aop:
       auto: true

